### ISSUE TITLE
Support user-provided retry (polling) policy

### ISSUE THREAD

**Issue by binkley** [jayway/awaitility#36]
Awaitility is almost ideal for our purposes with one exception: we'd like to back off exponentially (or perhaps with a Fibonacci sequence) in our polling rather than use a fixed interval.

I may have missed it, but I didn't see a way in the docs or code to provide my own retry policy.

**Comment by johanhaleby** [comment]
Very interesting idea. But what should the API look like? Perhaps something like:

```java
await().pollInterval(Backoff.FIBONACCI, MILLISECONDS).until(() -> ..)
```

Or should it be a new method?

```java
await().pollBackoff(Backoff.FIBONACCI, MILLISECONDS).until(() -> ..)
```

**Comment by binkley** [comment]
I might overload `pollInterval` to take either `long` and `TimeUnit` (the current case with a repeating interval) or `TimeUnit` and `long...` in that order for the custom case.  On second though, a different method name would be cleaner that flipping the args.  :-)

An even more extensible approach is what you suggest, providing a SAM interface which streams TimeUnit/long pairs.  Perhaps?

```java
public final class Backoff {
    public final TimeUnit unit;
    public final long amount;
}

public builder-stage pollInterval(final Stream<Backoff> intervals) { ... }
```

**Comment by johanhaleby** [comment]
I would be very interested to include something like this in Awaitility but it needs to retain backward compatibility and work on Java 5.

**Comment by johanhaleby** [comment]
A cool thing with streams would be that you could generate infinite sequences based on a function and a start value. That way Awaitility could just get the next value of the sequence for each "poll". Perhaps this would be a feature for Java 9? (I heard you can ship two different API's in Java 9 somehow and Java will pick the right one based on the JVM version, not sure how this works yet though).

**Comment by johanhaleby** [comment]
I've started to implement it now. You can do for example:

```java
await().with().pollInterval(new FibonacciPollInterval()).until(() -> Assertions.assertThat(fakeRepository.getValue()).isEqualTo(1));
````

or:

```java
await().with().pollInterval((__, previous) -> previous.times(2)).until(() -> Assertions.assertThat(fakeRepository.getValue()).isEqualTo(1));
```

The default poll interval has been refactored to use the `ConstantPollInterval`. Things are not perfect. For example we should probably get rid of the poll delay as it's implemented today. It should probably just be a start value of all `PollInterval`s. I've pushed this to the `pollinterval` branch. Please try it out and tell me what you think so far. All tests don't pass yet so build it with `mvn clean install -Dmaven.test.skip=true`.

**Comment by johanhaleby** [comment]
I'm thought a bit more about poll delay and poll interval. If poll interval is always represented by a `PollInterval` we actually wouldn't need a poll delay.. For example `ConstanstPollInterval` could also include an initial delay as a second parameter. For example:

```java
await().pollInterval(new Duration(200, MILLISECONDS), new Duration(100, MILLISECONDS)).until(..)
```

where 100 millis could represent the initial poll delay. This could also be backwards compatible:

```java
await().pollInterval(200, MILLISECONDS).pollDelay(100, MILLISECONDS).until(..)
```

would internally just create a `ConstantPollInterval` under the covers. The question is what should happen if one specifies something like this:

```java
await().pollDelay(400, MILLISECONDS).pollInterval(new Duration(200, MILLISECONDS), new Duration(100, MILLISECONDS)).until(..)
```

And what if you do:

```java
await().pollDelay(400, MILLISECONDS).pollInterval(new FibonacciPollInterval()).until(..)
```

Perhaps the simplest solution would be that we ALWAYS add the initial poll delay if this is explicitly specified by the user as in the two examples above. So if we take the first case the initial poll delay would thus be 500 milliseconds (400 + 100). The default delay for `ConstantPollInterval` would thus have to be zero in order to be backward compatible and to avoid special cases: I.e. 

```java
await().pollInterval(200, MILLISECONDS).pollDelay(100, MILLISECONDS).until(..)
```

would delay 100 milliseconds and `pollInterval(200, MILLISECONDS)` would just create a new instance of `ConstantPollInterval` of 200 milliseconds with an initial delay of zero. Poll delay would thus still be a first class thing in Awaitility in the future.

Btw, perhaps we should rename `ConstantPollInterval` to `FixedPollInterval`?

**Comment by johanhaleby** [comment]
Hmm perhaps it would be even simpler if a `PollInterval` can never include a poll delay at all.. Thus poll delay is used for poll delay and poll interval is used for the poll interval. Makes sense to me :)

**Comment by johanhaleby** [comment]
I've made these changes now.

**Comment by binkley** [comment]
Much appreciative of your work.  We've definitely moved to "buy" rather than "roll your own".  :-)

**Comment by johanhaleby** [comment]
Glad you found it useful :)
